#!/bin/bash

# R is for assigning a random number to it
R=0
DIRS=()

#copy motd into /etc/
cat /tmp/scenario-rogue-stranger/motd/intro-message.txt >> /etc/motd

for FILE in /home/*; do
    if [[ -d $FILE ]]; then
        DIRS+=( "$FILE" )
        echo $FILE
    fi
done
for studentDIR in "${DIRS[@]}"; do
    player=$(basename $studentDIR)
    cp /tmp/scenario-rogue-stranger/motd/intro-message.txt /$studentDIR/

    # Add an alias for all home directories
    cat /tmp/scenario-rogue-stranger/cd_alias >> /$studentDIR/.bashrc

    # Copy the file hierarchy to each home directory
    cp -R /tmp/scenario-rogue-stranger/files/* /$studentDIR/

done
rm -r /tmp/scenario-rogue-stranger
